config/routes.rb
Rails.application.routes.draw do
  resources :articles
  resources :categories

  root 'welcome#index'
  get 'user/profile' => 'user#profile'
  post 'user/submit' => 'user#submit'
  get 'user/user_category' => 'user#user_category'
  get 'user/user_all_category' => 'user#user_all_category'
  get 'user/is_logged_in' => 'user#is_logged_in'
  get 'user/articles' => 'user#articles'

  match 'auth/:provider/callback', to: 'sessions#create', via: [:get, :post]
  match 'auth/failure', to: redirect('/'), via: [:get, :post]
  match 'signout', to: 'sessions#destroy', as: 'signout', via: [:get, :post]

end

app/models/article.rb
class Article < ActiveRecord::Base
  has_and_belongs_to_many :categories
  has_many :images
  validates :title, uniqueness: { case_sensitive: false }
end

app/models/category.rb
class Category < ActiveRecord::Base
  has_and_belongs_to_many :articles
  has_and_belongs_to_many :users
end

app/models/image.rb
class Image < ActiveRecord::Base
  belongs_to :article
end

app/models/user.rb
class User < ActiveRecord::Base
  has_and_belongs_to_many :categories

  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.provider = auth.provider
      user.uid = auth.uid
      user.name = auth.info.name
      user.image = auth.info.image
      user.token = auth.credentials.token
      user.expires_at = Time.at(auth.credentials.expires_at)
      user.save
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :null_session, if: Proc.new { |c| not c.request.format.json? }

  private

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
  helper_method :current_user
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: [:show, :edit, :update, :destroy]

  # GET /articles
  # GET /articles.json
  def index
    @articles = Article.order("pub_date DESC")
    @categories = Category.all
    if params[:category]
      @articles = Article.joins(:categories).where("categories.category_name" => params[:category]).order("pub_date DESC")
    end
  end

  # GET /articles/1
  # GET /articles/1.json
  def show
    @categories = Article.find_by_id(params[:id]).categories
    @images = Article.find_by_id(params[:id]).images
    render 'show', layout: 'article'
  end

  # GET /articles/new
  def new
    @article = Article.new
  end

  # GET /articles/1/edit
  def edit
  end

  # POST /articles
  # POST /articles.json
  def create
    @article = Article.new(article_params)

    @article.categories  << Category.find(params[:article][:categories])

    respond_to do |format|
      if @article.save
        format.html { redirect_to @article, notice: 'Article was successfully created.' }
        format.json { render :show, status: :created, location: @article }
      else
        format.html { render :new }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /articles/1
  # PATCH/PUT /articles/1.json
  def update

    respond_to do |format|
      if @article.update(article_params)
        format.html { redirect_to @article, notice: 'Article was successfully updated.' }
        format.json { render :show, status: :ok, location: @article }
      else
        format.html { render :edit }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /articles/1
  # DELETE /articles/1.json
  def destroy
    @article.destroy
    respond_to do |format|
      format.html { redirect_to articles_url, notice: 'Article was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_article
      @article = Article.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def article_params
      params.require(:article).permit(:title, :author, :pub_date, :link_identifier, :main_img_url, :content, :category_ids => [])
    end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: [:edit, :update, :destroy]

  def index
    @categories = Category.all
  end

  def new
    @category = Category.new
  end

  def edit
  end

  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        format.html {redirect_to categories_url, notice: 'Category was successfully created.'}
        format.json {render :index, status: :created, location: categories_url}
      else
        format.html {render :new}
        format.json {render json: @category.errors, status: :unprocessable_entity}
      end
    end
  end

  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html {redirect_to categories_url, notice: 'Category was successfully updated.'}
        format.json {render :index, status: :ok, location: categories_url}
      else
        format.html {render :edit}
        format.json {render json: @category.errors, status: :unprocessable_entity}
      end
    end
  end

  def destroy
    @category.destroy
    respond_to do |format|
      format.html {redirect_to categories_url, notice: 'Category was successfully destroyed.'}
      format.json {head :no_content}
    end
  end

  private

    def set_category
      @category = Category.find(params[:id])
    end

    def category_params
      params.require(:category).permit(:category_name, :user_ids => [])
    end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    user = User.from_omniauth(env['omniauth.auth'])
    session[:user_id] = user.id
    redirect_to root_path
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_path
  end
end

app/controllers/user_controller.rb
class UserController < ApplicationController
  def profile
    @category = Category.all
  end

  def user_category
    @user_category = current_user.categories.order("category_name ASC")
  end

  def user_all_category
    all_category = Category.all
    user_category = current_user.categories

    @user_all_category = all_category.order("category_name ASC") - user_category
  end

  def submit
    current_user.categories.destroy_all
    params[:data].each do |data|
      c = Category.where(id: data[:id])
      current_user.categories << c
    end
    render nothing: true
  end

  def articles
    user_articles = []
    user_category = current_user.categories
    user_category.each do |c|
      c.articles.each do |a|
        user_articles.push(a)
      end
    end
    @user_articles = user_articles.uniq.sort_by {|a| a.pub_date}.reverse!
  end

  def is_logged_in
    render json: {is_logged_in: (not current_user.nil?)}
  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    @article = Article.all.shuffle
    @category = Category.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/articles/_form.html.erb
<%= form_for @article, :html => {:multipart => true} do |f| %>
  <% if @article.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@article.errors.count, "error") %> prohibited this article from being saved:</h2>

      <ul>
      <% @article.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :author %><br>
    <%= f.text_field :author %>
  </div>
    <div class="field">
    <%= f.label :category %><br>
    <%= f.collection_select(:category_ids, Category.all.order("category_name ASC"), :id, :category_name, {:include_hidden => false}, {:multiple =>true})%>

  </div>
  <div class="field">
    <%= f.label :pub_date %><br>
    <%= f.date_select :pub_date %>
  </div>
  <div class="field">
    <%= f.label :link_identifier %><br>
    <%= f.text_area :link_identifier %>
  </div>
  <div class="field">
    <%= f.label :main_img_url %><br>
    <%= f.text_area :main_img_url %>
  </div>
  <div class="field">
    <%= f.label :content %><br>
    <%= f.text_area :content %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/articles/edit.html.erb
<h1>Editing article</h1>

<%= render 'form' %>

<%= link_to 'Show', @article %> |
<%= link_to 'Back', articles_path %>

app/views/articles/index.html.erb
<h1>Listing articles</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Author</th>
      <th>Category</th>
      <th>Pub date</th>
      <th>Link identifier</th>
      <th>Main img url</th>
      <!-- <th>Content</th> -->
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @articles.each do |article| %>
      <tr>
        <td><%= article.title %></td>
        <td><%= article.author %></td>
        <td>
          <ul>
        <% article.categories.pluck(:category_name).each do |c| %>
            <li><%= c %></li>
        <% end %>
          </ul>
        </td>
        <td><%= article.pub_date %></td>
        <td><%= article.link_identifier %></td>
        <td><%= article.main_img_url %></td>
        <!-- <td><%= article.content %></td> -->
        <td><%= link_to 'Show', article %></td>
        <td><%= link_to 'Edit', edit_article_path(article) %></td>
        <td><%= link_to 'Destroy', article, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Article', new_article_path %>

app/views/articles/new.html.erb
<h1>New article</h1>

<%= render 'form' %>

<%= link_to 'Back', articles_path %>

app/views/articles/show.html.erb
<%= link_to 'Edit', edit_article_path(@article) %> |
<%= link_to 'Back', articles_path %>

<% publisher = @article.link_identifier[/[a-z]{1,}\Wcom/] %>
<div class="<%=publisher[/^[a-z]{1,}/]%> container">


  <p id="notice"><%= notice %></p>


  <div class="row">
    <hr class="top-hr" />
      <div class="headline">
        <div class="col-xs-3 source"><%= link_to publisher[/^[a-z]{1,}/].upcase, @article.link_identifier, :target => "_blank" %></div>
        <div class="col-xs-6 logo"><%= link_to(raw("<i class='fa fa-newspaper-o fa-1x'></i> READABLE"), root_url) %></div>
        <div class="col-xs-3 category"><%= @categories.first.category_name.upcase %></div>
      </div>
  </div>


  <div class="row">
    <div class="col-sx-12">
      <hr class="bottom-hr" />
      <div class="jumbotron main-img-url">
        <div class="img-title">
          <h1 og:title><%= @article.title %></h1>
          <%= image_tag @article.main_img_url %>
        </div>
      </div>
    </div>
  </div>

  <div class="row content">
    <div class="col-md-3 side-bar">

      <div class="social">
        <div class="fb-share-button" data-href="http://readable-app.herokuapp.com/articles/<%= @article.id %>" data-layout="icon"></div>
        <i class="fa fa-facebook-square fa-3x"></i>
        <i class="fa fa-twitter-square fa-3x"></i>
        <i class="fa fa-pinterest-square fa-3x"></i>
        <i class="fa fa-envelope fa-3x"></i>
      </div>

      <div class="written-by">
        <p><strong>WRITTEN BY</strong></p>
        <p><%= @article.author %></p>
      </div>

      <div class="pub-date">
        <p><strong>PUBLISHED DATE</strong></p>
        <p><%= @article.pub_date.strftime("%A, %b %e %Y") %></p>
      </div>

      <div class="content-category">
        <p><strong>CATEGORY</strong></p>
        <% @categories.order("category_name ASC").each do |category| %>
        <p><%= category.category_name %></p>
        <% end %>
      </div>

      <div class="source-link">
        <p><strong><%= link_to "SOURCE", @article.link_identifier, :target => "_blank" %></strong></p>
      </div>

    </div>


    <div class="col-md-9 main-content">
      <%= raw @article.content %>
    </div>

  </div>

  <br />


</div>

app/views/categories/_form.html.erb
<%= form_for @category, :html => {:multipart => true} do |f| %>
  <% if @category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
      <% @category.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :category_name %><br>
    <%= f.text_field :category_name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/categories/edit.html.erb
<h1>Editing category</h1>

<%= render 'form' %>

<%= link_to 'Back', categories_path %>

app/views/categories/index.html.erb
<h1>Listing categories</h1>

<table>
  <thead>
    <tr>
      <th>ID</th>
      <th>Category Name</th>
      <th colspan="2"></th>
    </tr>
  </thead>

  <tbody>
    <% @categories.order("category_name ASC").each do |category| %>
      <tr>
        <td><%= category.id %></td>
        <td><%= category.category_name %></td>
        <td><%= link_to 'Edit', edit_category_path(category) %></td>
        <td><%= link_to 'Destroy', category, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Category', new_category_path %>

app/views/categories/new.html.erb
<h1>New category</h1>

<%= render 'form' %>

<%= link_to 'Back', categories_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>

  <title>ReadableApp</title>
  <%= stylesheet_link_tag '//maxcdn.bootstrapcdn.com/bootstrap/3.3.0/css/bootstrap.min.css' %>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <link href="//maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css" rel="stylesheet">
  <link href='//fonts.googleapis.com/css?family=Raleway:500,900,200' rel='stylesheet' type='text/css'>
  <link href='//fonts.googleapis.com/css?family=Montserrat:400,700' rel='stylesheet' type='text/css'>
  <link href='//fonts.googleapis.com/css?family=Roboto:400,100,100italic,300,300italic,400italic,500,500italic,700,700italic,900,900italic' rel='stylesheet' type='text/css'>
</head>

<body ng-app="readableApp" class="landing-body">

  <%= yield %>

  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag '//maxcdn.bootstrapcdn.com/bootstrap/3.3.0/js/bootstrap.min.js' %>
</body>
</html>

app/views/layouts/article.html.erb
<!DOCTYPE html>
<html>
<head>

  <title>ReadableApp </title>
  <%= stylesheet_link_tag '//maxcdn.bootstrapcdn.com/bootstrap/3.3.0/css/bootstrap.min.css' %>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <link href="//maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css" rel="stylesheet">
  <link href='//fonts.googleapis.com/css?family=Raleway:500,900,200' rel='stylesheet' type='text/css'>
  <link href='//fonts.googleapis.com/css?family=Montserrat:400,700' rel='stylesheet' type='text/css'>
  <link href='//fonts.googleapis.com/css?family=Roboto:400,100,100italic,300,300italic,400italic,500,500italic,700,700italic,900,900italic' rel='stylesheet' type='text/css'>
</head>

<body ng-app="readableApp">

  <%= yield %>

  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag '//maxcdn.bootstrapcdn.com/bootstrap/3.3.0/js/bootstrap.min.js' %>
</body>
</html>

app/views/user/profile.html.erb
<div ng-controller="UserCtrl" class="container">
  <h1>User Preference</h1>

  <%= image_tag current_user.image %>
  <%= current_user.name %>

  <div class="row">
    <div class="col-xs-2 col-xs-offset-10">
      <button type="button" class="btn btn-default" aria-label="Left Align" ng-click="userSubmit()">
        <span class="glyphicon glyphicon-ok" aria-hidden="true"></span>
        Save Selection
      </button>
    </div>
  </div>

  <div class="row">
    <div class="col-xs-6 category-container">
      <h3>All Categories</h3>
      <div ng-repeat="category in allCategories" class="category-name checkbox">
        <button type="button" class="btn btn-default" aria-label="Left Align" ng-click="addCategory(category, $index)">
          <div>{{category.category_name}}</div>
          <span class="glyphicon glyphicon-plus" aria-hidden="true"></span>
        </button>
      </div>
    </div>

    <div class="col-xs-6 category-container">
      <h3>Selected Categories</h3>
      <div ng-repeat="category in userCategories" class="category-name checkbox">
        <button type="button" class="btn btn-default" aria-label="Left Align" ng-click="removeCategory(category, $index)">
          <div>{{category.category_name}}</div>
          <span class="glyphicon glyphicon-minus" aria-hidden="true"></span>
        </button>
      </div>
    </div>

  </div>

</div>

app/views/welcome/_article_modal.html.erb
<div id="fb-root"></div>
<script>(function(d, s, id) {
  var js, fjs = d.getElementsByTagName(s)[0];
  if (d.getElementById(id)) return;
  js = d.createElement(s); js.id = id;
  js.src = "//connect.facebook.net/en_US/sdk.js#xfbml=1&appId=594370410691941&version=v2.0";
  fjs.parentNode.insertBefore(js, fjs);
}(document, 'script', 'facebook-jssdk'));</script>



<script type="text/javascript">
window.twttr=(function(d,s,id){var t,js,fjs=d.getElementsByTagName(s)[0];if(d.getElementById(id)){return}js=d.createElement(s);js.id=id;js.src="https://platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);return window.twttr||(t={_e:[],ready:function(f){t._e.push(f)}})}(document,"script","twitter-wjs"));
</script>

<div class="modal fade bs-article-view" tabindex="-1" role="dialog" aria-labelledby="myLargeModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-lg">
    <div class="modal-content container">

      <div class="modal-header">
        <div class="row">
          <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">×</span><span class="sr-only">Close</span></button>
          <div class="img-title modal-title">
            <h4>{{article.title}}</h4>
          </div>
        </div>
      </div>

      <div class="modal-body">
        <div class="img-title">
          <img src="{{article.main_img_url}}" alt="{{article.link_identifier}}"></img>
        </div>

        <div class="row content">
          <div class="col-xs-2 side-bar">

            <div class="social" id="facebook">
              <div class="fb-share-button" data-href="http://readable-app.herokuapp.com/#/articles/{{article.id}}" data-layout="button"></div>
            </div>

            <div class="social" id="twitter">
              <a class="twitter-share-button" href="http://readable-app.herokuapp.com/#/articles/{{article.id}}" data-via="{{article.title}}" data-count="none"></a>
            </div>

            <div class="written-by">
              <p><strong>WRITTEN BY</strong></p>
              <p>{{article.author}}</p>
            </div>

            <div class="pub-date">
              <p><strong>PUBLISHED DATE</strong></p>
              <p>{{article.pub_date}}</p>
            </div>

            <div class="content-category">
              <p><strong>CATEGORY</strong></p>

              <p ng-repeat="category in article.categories">{{category.category_name}}</p>
            </div>

            <div class="source-link">
              <p><strong><a href="{{article.link_identifier}}" target ="_blank">Source</a></strong></p>
            </div>

          </div>

          <div class="col-xs-10 {{articleClass}}">
            <div class="main-content" ng-bind-html="article.content">

            </div>
          </div>

        </div>

      </div>

    </div>
  </div>
</div>

app/views/welcome/_collapse.html.erb
<!-- ng-if user is logged in -->

<div id="collapseOne" class="panel-collapse collapse" role="tabpanel" aria-labelledby="headingOne" ng-if="userLoggedIn">
  <div class="panel-body collapse-container">
    <!-- ... -->
    <div class="container">

      <div class="row">
        <div class="col-xs-6 category-container panel panel-info">
          <div class="panel-heading">
            <h3 class="panel-title">All Categories</h3>
          </div>
          <div class="panel-body">
            <div ng-repeat="category in allCategories" class="category-name checkbox btn-group">
              <button type="button" class="btn btn-warning" aria-label="Left Align" ng-click="addCategory(category, $index)">
                <div>{{category.category_name }} <i class="fa fa-check-circle fa-lg"></i></div>
              </button>
            </div>
          </div>
        </div>

        <div class="col-xs-6 category-container panel panel-primary">
          <div class="panel-heading">
            <h3 class="panel-title">Selected Categories</h3>
            <div class="btn-group btn-group-xs">
              <button type="button" class="btn btn-danger" aria-label="Left Align" ng-click="userSubmit()" data-toggle="collapse">
                <span class="glyphicon glyphicon-ok" aria-hidden="true"></span>
                SAVE
              </button>
            </div>
          </div>
          <div class="panel-body">
            <div ng-repeat="category in userCategories" class="category-name checkbox btn-group">
              <button type="button" class="btn btn-success" aria-label="Left Align" ng-click="removeCategory(category, $index)">
                <div>{{category.category_name }} <i class="fa fa-times-circle fa-lg"></i></div>
              </button>
            </div>
          </div>
        </div>

      </div>
    </div>


    <!-- ... -->
  </div>
</div>

<!-- ng-if user is not logged in -->

<div id="collapseOne" class="panel-collapse collapse in ng-cloak" ng-cloak role="tabpanel" aria-labelledby="headingOne" ng-if="!userLoggedIn">
  <div class="panel-body collapse-container">
    <!-- ... -->
    <div class="container">

      <div class="row">
        <div class="col-xs-6 col-xs-offset-3">

          <div class="panel panel-primary user-logout">

            <div class="panel-heading">
              <h3 class="panel-title user-logout">Welcome to <i class='fa fa-newspaper-o fa-lg'></i> READABLE!</h3>
            </div>

            <div class="panel-body user-logout">
              <br>
              <br>
              <br>
              <p>Sign in here using your
              <span class="label label-default"><%= link_to raw("<i class='fa fa-facebook-square fa-lg'></i> Facebook"), "/auth/facebook", id: "sign_in" %></span></p>
              <br>
              <br>
              <br>
              <button class="reject"><a data-toggle="collapse" href="#collapseOne">or continue without signing in</a></button>
            </div>
          </div>

        </div>
      </div>

    <!-- ... -->
  </div>
</div>

app/views/welcome/_menu.html.erb
<nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <button type="button" class="navbar-toggle collapsed btn btn-info visible-xs hidden-sm hidden-md hidden-lg" ng-click="showMyArticles()" ng-hide="!userLoggedIn">
        <i class="fa fa-heart fa-lg"></i>
      </button>

      <button type="button" class="navbar-toggle collapsed btn btn-primary visible-xs hidden-sm hidden-md hidden-lg" ng-click="showAllArticles()">
        <i class="fa fa-dot-circle-o fa-lg"></i>
      </button>
      <%= link_to(raw("<i class='fa fa-newspaper-o fa-lg'></i> READABLE"), root_path, :class => "navbar-brand readable-logo") %>
    </div>

    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li class="active"><a data-toggle="collapse" data-parent="#accordion" href="#collapseOne" aria-expanded="true" aria-controls="collapseOne">What would you like to read? <span class="glyphicon glyphicon-chevron-down" aria-hidden="true"></span></a></li>
      </ul>

      <% if current_user %>
        <ul class="nav navbar-nav navbar-right welcome-user" id="user-widget">
          <li><%= link_to "Sign out", signout_path, id: "sign_out" %></li>
        </ul>

        <p class="navbar-text navbar-right welcome-user hidden-xs hidden-sm hidden-md">Welcome <strong><%= current_user.name %></strong>!</p>

        <ul class="nav navbar-nav navbar-right welcome-user hidden-xs hidden-sm hidden-md" id="user-widget">
          <li><%= image_tag current_user.image %></li>
        </ul>
      <% else %>
        <ul class="nav navbar-nav navbar-right" id="user-widget">
          <li class="welcome-user"><%= link_to "Sign in with Facebook", "/auth/facebook", id: "sign_in" %></li>
        </ul>
      <% end %>

      <form class="navbar-form navbar-right" role="search" _lpchecked="1">
        <div class="form-group">
          <button type="button" class="btn btn-info hidden-xs" ng-click="showMyArticles()" ng-hide="!userLoggedIn">
            <i class="fa fa-heart fa-lg"></i>
          </button>

          <button type="button" class="btn btn-primary hidden-xs" ng-click="showAllArticles()">
            <i class="fa fa-dot-circle-o fa-lg"></i>
          </button>
          <input type="text" ng-model="search" class="form-control hidden-xs hidden-sm hidden-md" placeholder="Search keywords" autocomplete="off">
        </div>
      </form>

    </div>
  </div>

  <%= render partial: 'welcome/collapse' %>
</nav>

app/views/welcome/index.html.erb
<div class="landing-landing" ng-controller="ArticleCtrl">

  <%= render partial: 'menu'  %>

  <div class="landing-container">
    <%= video_tag "background.webm", :autobuffer => true, :autoplay => true, :loop => true, :poster => "background.png", :id => "bgvid" %>
    <div class="video-wrapper "></div>

    <div class="landing-articles container articles-container">
      <!-- <div class="container articles-container"> -->
        <div class="row articles-container">
          <div class="col-xs-3 col-sm-3 col-md-3 col-lg-3 readable-article" ng-repeat="article in articles | filter: search | filter: { categories:category||undefined }">
            <div class="landing-main-img-url"><img ng-src="{{article.main_img_url}}" alt="{{article.title}}"></div>
            <div class="landing-title"><h1><a href="#/articles/{{article.id}}">{{article.title}}</a></h1></div>
            <span class="label label-primary category-pills" ng-repeat="category in article.categories" ng-click="pillFilter(category.category_name)">{{category.category_name}}</span>
          </div>
        </div>
      <!-- </div> -->
    </div>
  </div>

  <%= render partial: 'article_modal'  %>

</div>